require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/lease_agreements", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # LeaseAgreement. As you add validations to LeaseAgreement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      LeaseAgreement.create! valid_attributes
      get lease_agreements_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      lease_agreement = LeaseAgreement.create! valid_attributes
      get lease_agreement_url(lease_agreement)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_lease_agreement_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      lease_agreement = LeaseAgreement.create! valid_attributes
      get edit_lease_agreement_url(lease_agreement)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new LeaseAgreement" do
        expect {
          post lease_agreements_url, params: { lease_agreement: valid_attributes }
        }.to change(LeaseAgreement, :count).by(1)
      end

      it "redirects to the created lease_agreement" do
        post lease_agreements_url, params: { lease_agreement: valid_attributes }
        expect(response).to redirect_to(lease_agreement_url(LeaseAgreement.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new LeaseAgreement" do
        expect {
          post lease_agreements_url, params: { lease_agreement: invalid_attributes }
        }.to change(LeaseAgreement, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post lease_agreements_url, params: { lease_agreement: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested lease_agreement" do
        lease_agreement = LeaseAgreement.create! valid_attributes
        patch lease_agreement_url(lease_agreement), params: { lease_agreement: new_attributes }
        lease_agreement.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the lease_agreement" do
        lease_agreement = LeaseAgreement.create! valid_attributes
        patch lease_agreement_url(lease_agreement), params: { lease_agreement: new_attributes }
        lease_agreement.reload
        expect(response).to redirect_to(lease_agreement_url(lease_agreement))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        lease_agreement = LeaseAgreement.create! valid_attributes
        patch lease_agreement_url(lease_agreement), params: { lease_agreement: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested lease_agreement" do
      lease_agreement = LeaseAgreement.create! valid_attributes
      expect {
        delete lease_agreement_url(lease_agreement)
      }.to change(LeaseAgreement, :count).by(-1)
    end

    it "redirects to the lease_agreements list" do
      lease_agreement = LeaseAgreement.create! valid_attributes
      delete lease_agreement_url(lease_agreement)
      expect(response).to redirect_to(lease_agreements_url)
    end
  end
end
