require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/prospects", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Prospect. As you add validations to Prospect, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Prospect.create! valid_attributes
      get prospects_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      prospect = Prospect.create! valid_attributes
      get prospect_url(prospect)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_prospect_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      prospect = Prospect.create! valid_attributes
      get edit_prospect_url(prospect)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Prospect" do
        expect {
          post prospects_url, params: { prospect: valid_attributes }
        }.to change(Prospect, :count).by(1)
      end

      it "redirects to the created prospect" do
        post prospects_url, params: { prospect: valid_attributes }
        expect(response).to redirect_to(prospect_url(Prospect.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Prospect" do
        expect {
          post prospects_url, params: { prospect: invalid_attributes }
        }.to change(Prospect, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post prospects_url, params: { prospect: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested prospect" do
        prospect = Prospect.create! valid_attributes
        patch prospect_url(prospect), params: { prospect: new_attributes }
        prospect.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the prospect" do
        prospect = Prospect.create! valid_attributes
        patch prospect_url(prospect), params: { prospect: new_attributes }
        prospect.reload
        expect(response).to redirect_to(prospect_url(prospect))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        prospect = Prospect.create! valid_attributes
        patch prospect_url(prospect), params: { prospect: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested prospect" do
      prospect = Prospect.create! valid_attributes
      expect {
        delete prospect_url(prospect)
      }.to change(Prospect, :count).by(-1)
    end

    it "redirects to the prospects list" do
      prospect = Prospect.create! valid_attributes
      delete prospect_url(prospect)
      expect(response).to redirect_to(prospects_url)
    end
  end
end
